### ISSUE TITLE
Black frame around axis when moving vertices 

### ISSUE THREAD

**Issue by elkaps** [JuliaPlots/GraphMakie.jl#5] opened 2021-04-10 15:44 UTC
I have no idea where it's coming from but when moving a vertex this black frame shows up:

![black-border](https://user-images.githubusercontent.com/44770441/114275796-267a9500-9a24-11eb-9af5-f87b95d54086.png)

**Comment by SimonDanisch** [comment] 2021-04-12 10:50
Oh interesting :D Looks like the axis splines!

**Comment by hexaeder** [comment] 2021-08-10 09:49
I'll close this issue since i can not reproduce and the code is enterly different now anyway. Feel free to reopen though.

**Closed by hexaeder** 2021-08-10 09:49 UTC
